CONFIG_ZMK_KEYBOARD_NAME="flake"

# Set deep sleep to 30 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_EXT_POWER=y

# Lower the "press" debounce and keep the default value for the release.
# Default value for both options is 5
#CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
#CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# Boost Bluetooth TX power, also make Bluetooth stronger
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_MOUSE=n
